### ISSUE TITLE
Will this be able to handle images of 10-15 GB?

### ISSUE THREAD

**Issue by komzy** [foobar167/junkyard#2]
Hi there,

The codes you have provided for zooming are extremely educational for a newbie like me. Thanks for uploading them. 

I'm trying to work on a flexible zoom viewer on python 2.7 for reading TIFF images around the size of 15GB. Can your code (_zoom_huge_python2.7.py_) be able to handle such huge images?

**Comment by foobar167** [comment]
Hi!

There is special software to handle huge images of specific formats like [OpenSlide](https://openslide.org).

I'm using [Pillow](https://pillow.readthedocs.io/en/stable) Python package to open images. Thus my software can open Pillow [image file formats](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html). There are many of them, but **they are not designed to manage** 15GB files. Sorry.

The biggest files I've opened with my application was around **5GB in RAW** format and **1.7GB in PNG** format. That's not bad, but not enough for you.

And if the image is not in RAW format, it should be placed **completely inside** RAM memory of your computer. So you should have enough RAM on your computer to open JPG, PNG and other popular (but not designed to be huge) image formats.

P.S. Remember that [version 2.7 will retire in 2020](https://pythonclock.org/).

**Comment by foobar167** [comment]
Maybe in the future, I'll make support of 15GB files. However, there should be a different image manager, not a [Pillow](https://pillow.readthedocs.io/en/stable/).
